services:
  - type: web
    name: jotabeeli
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
